backend:
  name: github
  repo: lau1998/gatsby-blog  # GitLab存储库的路径
  branch: main
  // site_domain: ildaneta.dev # GitLab设置中的应用程序ID 

publish_mode: editorial_workflow
media_folder: 'static/assets/img'
public_folder: 'assets/img'

collections:
  - name: 'posts' # Used in routes, e.g., /admin/collections/blog
    label: 'posts' # 在UI中使用
    folder: 'posts' # 存储文档的文件夹的路径
    create: true # 允许用户在此集合中创建新文档
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # 文件名模板, e.g., YYYY-MM-DD-title.md
    fields: # 每个文档的字段，通常在前面
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: '标题', name: 'title', widget: 'string' }
      - { label: '文章描述', name: 'description', widget: 'string' }
      - {
          label: '时间',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD hh:mm:ss',
        }
      - { label: '图片', name: 'thumbnail', widget: 'image' }
      - {
          label: '分类',
          name: 'category',
          widget: 'select',
          options: ['Vue', 'JS', 'CSS', 'HTML', 'React', '随笔'],
        }
      - {
          label: '背景',
          name: 'background',
          widget: 'select',
          options:
            [
              { label: 'Vue', value: '#f26' },
              { label: 'JS', value: '#f7a5a6' },
              { label: 'CSS', value: '#7d669e' },
              { label: 'HTML', value: '#f77394' },
              { label: 'React', value: '#CD4C51' },
              { label: '随笔', value: '#e261e0' },
            ],
        }
      - { label: '主体内容', name: 'body', widget: 'markdown' }
